name: End-to-end cypress app tests
on: [push]

jobs:
  cypress-run:
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [14]
    runs-on: ${{ matrix.os }}
    name: E2E on Chrome on Node v${{ matrix.node }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Cypress run
        uses: cypress-io/github-action@v1
        with:
          browser: chrome
          config: pageLoadTimeout=100000,watchForFileChanges=false
          build: yarn build
          start: yarn start
          wait-on: http://localhost:3000
          wait-on-timeout: 120
          spec: cypress/integration/app/**/*
